# Generated by Django 3.2.25 on 2024-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
