# Generated by Django 3.2.25 on 2024-04-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='image_filter',
        ),
    ]
