# Generated by Django 3.2.25 on 2024-04-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20240410_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
    ]
