# Generated by Django 3.2.25 on 2024-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seecrets', '0002_seecret_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='seecret',
            name='category',
            field=models.CharField(choices=[('Love', 'Love'), ('Family', 'Family'), ('Money', 'Money'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
