# Generated by Django 3.2.25 on 2024-04-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seecrets', '0003_seecret_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seecret',
            name='image',
            field=models.ImageField(blank=True, default='../default_seecret_lmvjp0', null=True, upload_to='images/'),
        ),
    ]
