# Generated by Django 3.2.25 on 2024-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seecrets', '0004_alter_seecret_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seecret',
            name='image',
            field=models.ImageField(blank=True, default='../default_seecret_r48frc', null=True, upload_to='images/'),
        ),
    ]
