# Generated by Django 3.2.25 on 2024-04-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_comment_comment_seecret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='seecret',
            new_name='seecretid',
        ),
    ]
