# Generated by Django 3.2.25 on 2024-04-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_seecretid_comment_seecret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='seecret',
            new_name='post',
        ),
    ]
