# Generated by Django 3.2.25 on 2024-04-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_rename_seecret_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='seecret',
        ),
    ]
