# Generated by Django 3.2.25 on 2024-04-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_rename_post_comment_seecret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='seecret',
            new_name='seecretid',
        ),
    ]
