# Generated by Django 3.2.25 on 2024-03-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reach_out', '0002_rename_content_reach_out_reach_out_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reach_out',
            old_name='reach_out',
            new_name='reach_out_to',
        ),
    ]
