# Generated by Django 3.2.25 on 2024-04-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reach_out', '0003_rename_reach_out_reach_out_reach_out_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reach_out',
            old_name='reach_out_content',
            new_name='content',
        ),
    ]
