# Generated by Django 3.2.25 on 2024-04-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reach_out', '0003_rename_reach_out_reach_out_reach_out_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reach_out_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reach_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reach_out.reach_out')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
