# Generated by Django 3.2.25 on 2024-04-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reach_out_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reach_out_comment',
            old_name='content',
            new_name='reach_out_comment_content',
        ),
    ]
