# Generated by Django 3.2.25 on 2024-03-26 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seecrets', '0002_seecret_image_filter'),
        ('hugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hug',
            old_name='post',
            new_name='hug',
        ),
        migrations.AlterUniqueTogether(
            name='hug',
            unique_together={('owner', 'hug')},
        ),
    ]
