# Generated by Django 3.2.25 on 2024-04-11 03:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seecrets', '0004_alter_seecret_image'),
        ('hugs', '0002_auto_20240326_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hug',
            old_name='hug',
            new_name='seecret',
        ),
        migrations.AlterUniqueTogether(
            name='hug',
            unique_together={('owner', 'seecret')},
        ),
    ]
