# Generated by Django 3.2.25 on 2024-04-11 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seecrets', '0004_alter_seecret_image'),
        ('hugs', '0003_auto_20240411_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hug',
            old_name='seecret',
            new_name='hug',
        ),
        migrations.AlterUniqueTogether(
            name='hug',
            unique_together={('owner', 'hug')},
        ),
    ]
